version: '3'
services:
  kimchi-cloud-apigateway:
    container_name: kimchi-cloud-apigateway
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kimchi-network
    ports:
      - "443:443"
    
networks:
  kimchi-network:
    external: true


