server:
  ssl:
    enabled: true
#    key-alias: changeling
    key-store-password: changminidle1234
    key-store: classpath:changminidle.p12
    key-store-type: PKCS12

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true