spring:
  application:
    name: kimchi-apigateway-service

  profiles:
    active:
      - local

    group:
      local:
        - site-local

  cloud:
    gateway:
      routes:
        - id: kimchi-domain-app-service
          uri: lb://KIMCHI-DOMAIN-APP-SERVICE
          predicates:
            - Path=/domain/**, /login/**, /oauth2/**

        - id: kimchi-ai-app-service
          uri: lb://KIMCHI-AI-APP-SERVICE
          predicates:
            - Path=/ai/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka