spring:
  application:
    name: kimchi-apigateway-service

  profiles:
    active:
      - local

    group:
      local:
        - local-config

      dev:
        - dev-config

      prod:
        - prod-config


  cloud:
    gateway:
      routes:
        - id: kimchi-domain-app-service
          uri: lb://KIMCHI-DOMAIN-APP-SERVICE
          predicates:
            - Path=/domain/**, /login/**, /oauth2/**

        - id: kimchi-ai-app-service
          uri: lb://KIMCHI-AI-APP-SERVICE
          predicates:
            - Path=/ai/**