server:
  port: 9000 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: kimchi-apigateway-service

  cloud:
    gateway:
      routes:
        - id: kimchi-domain-app-service
          uri: lb://KIMCHI-DOMAIN-APP-SERVICE
          predicates:
            - Path=/domain/**

        - id: kimchi-ai-app-service
          uri: lb://KIMCHI-AI-APP-SERVICE
          predicates:
            - Path=/ai/**
